const artComponents = {
  light: {
    artObject: [
      "a candle scented by",
      "a spotlight the colour of",
      "a neon light the colour of",
      "a candle burning the length of ",
      "a torch simulating light from",
      "a skylight tinted the tones of",
      "matchsticks that burn the colour of",
      "streetlamps flickering live with",
      "a lighthouse beam spinning in time with",
      "a dimmer switch that adjusts the brightness of",
      "a solar flare containing all the light in",
      "traffic lights the colour of ",
      "a fireworks display recreating",
      "firecrackers filled with the elements of",
      "a lightbulb recreating",
      "a torch light simulating",
      "a disco-ball reflecting",
      "a pencil with lead the colour of",
    ],
    naturalElement: [
      "the calm after a storm",
      "light beaming through clouds",
      "the moon's halo",
      "elements of stars",
      "every comet in history",
      "old and new stars",
      "light in the universe",
      "space",
      "pulsar",
      "lightning storms",
      "newborn stars",
      "the martian twilight",
      "the furthest star",
      "the neptunian night",
      "all the stars combined",
      "journey through space",
      "the milkyway",
      "wildfire",
      "an erupting volcano",
      "raindrops bouncing off pavement in a moonsoon",
    ],
  },
  sound: {
    artObject: [
      "music bounced back from",
      "a jukebox playing ",
      "the sound of",
      "a mixing board playing",
      "an electric violin powered by",
      "a turntable rotating in time with",
      "the force of a geyser controlling",
      "a phone line to",
      "records of glacial ice played until the end of",
      "a mix tape of ",
    ],
    naturalElement: [
      "calm after a storm",
      "the last note of every song",
      "every sound",
      "melted ice caps",
      "a dying star",
      "distant glacier",
      "volume of music",
      "earth",
      "moonlight",
      "sunlight",
      "earth's deepest silences",
      "universe carved into a dot",
      "surface of the moon",
      "lightning",
      "an avalanche",
      "a drought",
      "snow in a blizzard",
    ],
  },
  time: {
    artObject: [
      "hourglasses filled with",
      "a calendar dated to",
      "a clock that tells",
      "the timeline of",
      "a watch displaying",
      "a talking clock reading",
      "a grandfather-clock showing",
      "a pendulum swinging in time with",
    ],
    naturalElement: [
      "the time since the big bang",
      "the number of times the sun has risen",
      "the time on all known planets",
      "the year the sun will die",
      "the ruins of lost cities",
      "the latest species to become extinct",
      "the eruptions of all earth's volcanos",
      "a sinking ship",
      "every felled tree",
    ],
  },
  video: {
    artObject: [
      "a live feed from",
      "a television channel transmitting",
      "television broadcasting",
      "a film projected via",
      "a phone line to",
      "a webcam at",
      "a live feed of",
      "the universe's lights switched off one by one by",
      "rewound and played back in real time,",
      "a vr headset that shows",
      "a telescope pointing at",
    ],
    naturalElement: [
      "the calm after a storm",
      "the speed of light slowed to absolute stillness",
      "galaxies colliding",
      "the edge of the expanding universe",
      "a distant glacier",
      "light from the first star",
      "darkness from the early universe ",
      "weather reports from past centuries",
      "weather reports from outer space",
      "the centre of a maelstrom",
      "the migration of Ngorongoro",
      "a migrating monarch butterfly",
    ],
  },
};

export default artComponents;
